version: "3.3"

services:
  web:
    image: laravel:8-apache-debug
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/var/www/html:delegated
    environment:
      APP_NAME: 'laravel_with_docker'
      APP_ENV: 'development'
      APACHE_DOCUMENT_ROOT: '/var/www/html/public'
      DB_HOST: 'db'
      DB_USERNAME: 'root'
      DB_PASSWORD: 'masterkey'
      DB_DATABASE: 'laravel_with_docker'
      DB_PORT: 3306
    volumes:
      - "./:/var/www/html"
    ports:
      - 8000:80
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: "masterkey"
      MYSQL_DATABASE: "laravel_with_docker"
    ports:
      - "3306:3306"