#!/bin/bash

apt-get update && apt-get install -y \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libpng-dev \
    zlib1g-dev \
    libicu-dev \
    g++ \
    git \
    zip \
    nano \
    libzip-dev \
    && rm -rf /var/lib/apt/lists/*
